### ISSUE TITLE
🐛Webhook HMAC is not verified due to downcasing

### ISSUE THREAD

**Issue by kurt-friedrich** [malomohq/shopify-rest-elixir#2]
Webhook events are failing HMAC verification due to the computed `digest` being down-cased, while the header is not:
https://github.com/malomohq/shopify-rest-elixir/blob/master/lib/shopify/rest.ex#L102

FYI OAuth requests are still being verified correctly.

**Comment by kurt-friedrich** [comment]
@anthonator I'm not sure of the best way to resolve this, possibly down-casing the provided `hmac` before it is given to `ensure_hmac` here?

**Comment by anthonator** [comment]
A fix for has been included in v1.1.1

**Comment by kurt-friedrich** [comment]
Thanks!
